---
kind: pipeline
name: default

clone:
  # depth: 1
  disable: true

steps:
- name: clone
  image: docker:git
  commands:
  # 下载静态博客构建代码
  - git clone --depth=1 https://github.com/muxueqz/kun.git

- name: build
  image: nimlang/nim
  commands:
  # 编译静态博客构建工具
  - nimble install -y nwt markdown
  - cd kun
  - mkdir -pv dist/
  - nim c -d:release -o:dist/kun build.nim

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: GITHUB_API_KEY
    files: dist/kun
  when:
    event: tag
